spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: userservice-status-check
          uri: lb://userservice
          predicates:
            - Path=/userservice/user/status-check
          filters:
            - StripPrefix=1
        - id: userservice-secret-status-check
          uri: lb://userservice
          predicates:
            - Path=/userservice/app-health
          filters:
            - StripPrefix=1
            - RewritePath=/app-health, /user/secret-status-check
        - id:  userservice-create-user
          uri: lb://userservice
          predicates:
            - Path=/userservice/create-user
          filters:
            - StripPrefix=1
            - RewritePath=/create-user, /user/create




server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

