spring:
  application:
    name: userservice

  h2:
    console:
      enabled: true
      path: /h2-console  # http://localhost:8080/h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:C:/Users/FrankAboagye/IdeaProjects/microserviceprj1/userservice/data/sampledata
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
